import Foundation
import CBORCodable
import OrderedCollections
import SwiftNaCl

public struct Transaction: Serializable, TextEnvelopable {
    public static var TYPE: String { "Unwitnessed Tx ConwayEra" }
    public static var DESCRIPTION: String { "Generated by SwiftCardanoCore" }
    
    public var _payload: Data
    public var _type: String
    public var _description: String
    
    public var description: String {
        self.debugDescription
    }
    
    public var transactionBody: TransactionBody { didSet { originalCBOR = nil } }
    public var transactionWitnessSet: TransactionWitnessSet {
        didSet { originalCBOR = nil; originalWitnessSetCBOR = nil }
    }
    public var valid: Bool = true { didSet { originalCBOR = nil } }
    public var auxiliaryData: AuxiliaryData? = nil {
        didSet { originalCBOR = nil; originalAuxiliaryDataCBOR = nil }
    }

    /// The exact bytes this transaction was decoded from, for as long as it is
    /// unchanged since. Changing any part clears it.
    ///
    /// The body keeps its own bytes too (``TransactionBody/originalCBOR``), as
    /// do the witness set and auxiliary data here, so adding a witness to a
    /// decoded transaction re-encodes the witness set alone: the body — whose
    /// hash is the id every witness signs — and the auxiliary data — whose hash
    /// the body commits to — stay as written.
    public internal(set) var originalCBOR: Data? = nil
    /// The bytes the witness set was decoded from, while it is unchanged.
    public internal(set) var originalWitnessSetCBOR: Data? = nil
    /// The bytes the auxiliary data was decoded from, while it is unchanged.
    public internal(set) var originalAuxiliaryDataCBOR: Data? = nil

    /// Whether this was written in the Shelley to Mary shape,
    /// `[body, witnesses, auxiliary data]`, which has no validity flag.
    public internal(set) var isPreAlonzo: Bool = false {
        didSet { originalCBOR = nil }
    }
    
    enum CodingKeys: String, CodingKey {
        case transactionBody
        case transactionWitnessSet
        case valid
        case auxiliaryData
    }
    
    public var id: TransactionId? {
        return transactionBody.id
    }
    
    public init(
        transactionBody: TransactionBody,
        transactionWitnessSet: TransactionWitnessSet,
        valid: Bool = true,
        auxiliaryData: AuxiliaryData? = nil
    ) {
        self.transactionBody = transactionBody
        self.transactionWitnessSet = transactionWitnessSet
        self.valid = valid
        self.auxiliaryData = auxiliaryData
        self._payload = Data()
        self._type = Self.envelopeType(era: nil, witnessed: !transactionWitnessSet.isEmpty())
        self._description = Self.DESCRIPTION
        self._payload = (try? self.toCBORData()) ?? Data()
    }
    
    public init(payload: Data, type: String?, description: String?) throws {
        self = try Self.fromCBOR(data: payload)
        self._payload = payload
        self._description = description ?? Self.DESCRIPTION
        self._type = type ?? Self.envelopeType(
            era: nil, witnessed: !transactionWitnessSet.isEmpty()
        )
    }

    /// Decodes a transaction, keeping the bytes of it and of its parts, so that
    /// its id and its re-encoding are those of what was written.
    public static func fromCBOR(data: Data) throws -> Transaction {
        let scanner = CBORItemScanner(data)
        guard try scanner.end(ofItemAt: 0) == scanner.bytes.count else {
            throw CardanoCoreError.deserializeError("Trailing bytes after Transaction")
        }
        let spans = try scanner.elements(ofArrayAt: 0)
        var tx = try CBORDecoder().decode(Transaction.self, from: data)
        guard spans.count >= 3 else { return tx }

        let bytes = scanner.bytes
        tx.transactionBody.originalCBOR = bytes.subdata(in: spans[0])
        tx.originalWitnessSetCBOR = bytes.subdata(in: spans[1])
        let auxiliarySpan = tx.isPreAlonzo ? spans[2] : spans.count > 3 ? spans[3] : nil
        tx.originalAuxiliaryDataCBOR = auxiliarySpan.map { bytes.subdata(in: $0) }
        tx.originalCBOR = bytes
        return tx
    }

    public init(from cbor: Data) throws {
        self = try Self.fromCBOR(data: cbor)
    }

    /// The bytes this transaction was decoded from while it is unchanged;
    /// otherwise a fresh encoding that keeps the written bytes of every part
    /// that is unchanged.
    public func toCBORData(deterministic: Bool = false) throws -> Data {
        _ = deterministic
        if let originalCBOR { return originalCBOR }
        guard transactionBody.originalCBOR != nil
            || originalWitnessSetCBOR != nil
            || originalAuxiliaryDataCBOR != nil
        else {
            return try CBOREncoder().encode(self)
        }

        let encoder = CBOREncoder()
        var data = Data([isPreAlonzo ? 0x83 : 0x84])
        data.append(try transactionBody.toCBORData())
        data.append(try originalWitnessSetCBOR ?? encoder.encode(transactionWitnessSet))
        if !isPreAlonzo {
            data.append(valid ? 0xF5 : 0xF4)
        }
        if let originalAuxiliaryDataCBOR {
            data.append(originalAuxiliaryDataCBOR)
        } else if let auxiliaryData {
            data.append(try encoder.encode(auxiliaryData))
        } else {
            data.append(0xF6)
        }
        return data
    }

    /// The hash of the auxiliary data as written, which is what the body's
    /// `auxiliaryDataHash` must equal; `nil` when there is none.
    ///
    /// Re-encoding decoded metadata can change its bytes — map-key order,
    /// integer widths, string chunking — and with them the hash, so the
    /// written bytes are hashed while they are kept.
    public func auxiliaryDataHash() throws -> AuxiliaryDataHash? {
        guard let auxiliaryData else { return nil }
        guard let originalAuxiliaryDataCBOR else { return try auxiliaryData.hash() }
        return AuxiliaryDataHash(
            payload: try Hash().blake2b(
                data: originalAuxiliaryDataCBOR,
                digestSize: AUXILIARY_DATA_HASH_SIZE,
                encoder: RawEncoder.self
            )
        )
    }

    /// The text-envelope type cardano-cli gives a transaction of `era`:
    /// `Unwitnessed Tx <era>` before any witness is added, `Tx <era>` after.
    static func envelopeType(era: String?, witnessed: Bool) -> String {
        let era = era ?? "ConwayEra"
        return witnessed ? "Tx \(era)" : "Unwitnessed Tx \(era)"
    }

    /// The era named by a text-envelope type such as `Tx BabbageEra`, if any.
    static func era(ofEnvelopeType type: String) -> String? {
        type.split(separator: " ").last.map(String.init).flatMap {
            $0.hasSuffix("Era") && $0.count > 3 ? $0 : nil
        }
    }
    
    // MARK: - CBORSerializable
    
    public init(from primitive: Primitive) throws {
        guard case let .list(elements) = primitive else {
            throw CardanoCoreError.deserializeError("Invalid Transaction primitive: \(primitive)")
        }
        
        guard elements.count >= 3 else {
            throw CardanoCoreError.deserializeError("Transaction requires at least 3 elements")
        }
        
        // transactionBody (required)
        let transactionBody = try TransactionBody(from: elements[0])
        
        // transactionWitnessSet (required) - may be wrapped in a CBOR tag
        let transactionWitnessSet: TransactionWitnessSet
        if case let .cborTag(tagged) = elements[1] {
            // Witness set is wrapped in a CBOR tag, extract the value
            transactionWitnessSet = try TransactionWitnessSet(from: tagged.value)
        } else {
            // Witness set is not tagged
            transactionWitnessSet = try TransactionWitnessSet(from: elements[1])
        }
        
        // Shelley to Mary: [body, witnesses, auxiliary data / null], with no
        // validity flag. Alonzo onwards: [body, witnesses, valid, auxiliary data / null].
        let isPreAlonzo: Bool
        let valid: Bool
        let auxiliaryElement: Primitive?
        switch elements[2] {
        case .bool(let flag) where elements.count == 4:
            isPreAlonzo = false
            valid = flag
            auxiliaryElement = elements[3]
        case .bool(let flag) where elements.count == 3:
            // An Alonzo-shaped transaction with its auxiliary data left out.
            isPreAlonzo = false
            valid = flag
            auxiliaryElement = nil
        case _ where elements.count == 3:
            isPreAlonzo = true
            valid = true
            auxiliaryElement = elements[2]
        default:
            throw CardanoCoreError.deserializeError("Invalid valid field in Transaction")
        }

        var auxiliaryData: AuxiliaryData? = nil
        if let auxiliaryElement, auxiliaryElement != .null {
            auxiliaryData = try AuxiliaryData(from: auxiliaryElement)
        }
        
        self.init(
            transactionBody: transactionBody,
            transactionWitnessSet: transactionWitnessSet,
            valid: valid,
            auxiliaryData: auxiliaryData
        )
        self.isPreAlonzo = isPreAlonzo
    }
    
    
    public func toPrimitive() throws -> Primitive {
        if isPreAlonzo {
            return .list([
                try transactionBody.toPrimitive(),
                try transactionWitnessSet.toPrimitive(),
                try auxiliaryData?.toPrimitive() ?? .null
            ])
        }
        return .list([
            try transactionBody.toPrimitive(),
            try transactionWitnessSet.toPrimitive(),
            .bool(valid),
            try auxiliaryData?.toPrimitive() ?? .null
        ])
    }
    
    // MARK: - JSONSerializable
    
    public static func fromDict(_ dict: Primitive) throws -> Transaction {
        guard case let .orderedDict(dictValue) = dict else {
            throw CardanoCoreError.deserializeError("Invalid Transaction dict")
        }
        // Required fields
        guard let transactionBodyPrimitive = dictValue[.string(CodingKeys.transactionBody.rawValue)] else {
            throw CardanoCoreError.deserializeError("Missing transactionBody in Transaction")
        }
        let transactionBody = try TransactionBody.fromDict(transactionBodyPrimitive)
        
        guard let transactionWitnessSetPrimitive = dictValue[.string(CodingKeys.transactionWitnessSet.rawValue)] else {
            throw CardanoCoreError.deserializeError("Missing transactionWitnessSet in Transaction")
        }
        let transactionWitnessSet = try TransactionWitnessSet.fromDict(transactionWitnessSetPrimitive)
        
        guard let validPrimitive = dictValue[.string(CodingKeys.valid.rawValue)] else {
            throw CardanoCoreError.deserializeError("Missing valid field in Transaction")
        }
        
        let valid: Bool
        switch validPrimitive {
        case .bool(let boolValue):
            valid = boolValue
        case .int(let intValue):
            valid = intValue != 0
        case .uint(let uintValue):
            valid = uintValue != 0
        default:
            throw CardanoCoreError.deserializeError("Invalid valid field type in Transaction: \(validPrimitive)")
        }
        
        // Optional field
        var auxiliaryData: AuxiliaryData? = nil
        if let auxiliaryDataPrimitive = dictValue[.string(CodingKeys.auxiliaryData.rawValue)] {
            if case .null = auxiliaryDataPrimitive {
                auxiliaryData = nil
            } else {
                auxiliaryData = try AuxiliaryData.fromDict(auxiliaryDataPrimitive)
            }
        }
        
        return Transaction(
            transactionBody: transactionBody,
            transactionWitnessSet: transactionWitnessSet,
            valid: valid,
            auxiliaryData: auxiliaryData
        )
    }
    
    public func toDict() throws -> Primitive {
        var dict = OrderedDictionary<Primitive, Primitive>()
        
        dict[.string(CodingKeys.transactionBody.rawValue)] = try transactionBody.toDict()
        dict[.string(CodingKeys.transactionWitnessSet.rawValue)] = try transactionWitnessSet.toDict()
        dict[.string(CodingKeys.valid.rawValue)] = .bool(valid)
        
        if let auxiliaryData = auxiliaryData {
            dict[.string(CodingKeys.auxiliaryData.rawValue)] = try auxiliaryData.toDict()
        } else {
            dict[.string(CodingKeys.auxiliaryData.rawValue)] = .null
        }
        
        return .orderedDict(dict)
    }
    
    
    /// Serialize to JSON.
    ///
    /// The json output has three fields: "type", "description", and "cborHex".
    /// - Returns: JSON representation
    ///
    /// The type names the era this transaction was read with, when it came from
    /// a text envelope, and whether it carries any witness yet.
    public func toTextEnvelope() throws -> String? {
        let updatedType = Self.envelopeType(
            era: Self.era(ofEnvelopeType: _type),
            witnessed: !transactionWitnessSet.isEmpty()
        )
        
        let jsonString = """
        {
            "type": "\(updatedType)",
            "description": "\(self._description)",
            "cborHex": "\(try self.toCBORHex())"
        }
        """
        return jsonString
    }
    
    // MARK: - Equatable
    
    public static func == (lhs: Self, rhs: Self) -> Bool {
        return lhs.transactionBody == rhs.transactionBody &&
        lhs.transactionWitnessSet == rhs.transactionWitnessSet &&
        lhs.valid == rhs.valid &&
        lhs.auxiliaryData == rhs.auxiliaryData
    }

    /// Hashes what `==` compares — see ``TransactionBody/hash(into:)``, which the
    /// inherited payload-based implementation contradicted in the same way.
    public func hash(into hasher: inout Hasher) {
        hasher.combine(transactionBody)
        hasher.combine(valid)
    }
    
}
